resources = {
    "السنة الأولى": {
        "الفصل الأول": {
            "theoretical": {
                "⚡ فيزياء كهربائية": {
                    "gate1": [0],
                    "komit1": [0],
                    "student_written1": [107, 108, 109, 110, 111, 112],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "💻 برمجة 1": {
                    "gate1": [0],
                    "komit1": [61, 62, 63, 64, 65, 66, 127, 128],
                    "student_written1": [94, 95, 96, 97, 98, 99, 143],
                    "summaries1": [0],
                    "exams1": [16, 27],
                    "notes1": [0],
                },
                "📊 تحليل 1": {
                    "gate1": [0],
                    "komit1": [74, 75, 76, 77, 78, 79],
                    "student_written1": [131, 132],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "🖥 مبادئ عمل الحاسوب": {
                    "gate1": [0],
                    "komit1": [0],
                    "student_written1": [120, 121, 161, 162, 135],
                    "summaries1": [22, 23, 25],
                    "exams1": [8],
                    "notes1": [41],
                },
                "➗ جبر لا خطي": {
                    "gate1": [0],
                    "komit1": [53, 54, 55, 56, 57, 58, 59],
                    "student_written1": [78, 79, 80, 81, 82, 83, 84, 85, 86],
                    "summaries1": [0],
                    "exams1": [14, 26],
                    "notes1": [0],
                },
                "🇬🇧 لغة انجليزية 1": {
                    "gate1": [52],
                    "komit1": [6],
                    "student_written1": [0],
                    "summaries1": [0],
                    "exams1": [6],
                    "notes1": [39],
                },
                "🇸🇦 لغة عربية": {
                    "gate1": [41],
                    "komit1": [68],
                    "student_written1": [142],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
            },
            "practical": {
                "⚡ فيزياء كهربائية": {
                    "gate1": [0],
                    "komit1": [0],
                    "student_written1": [114, 115, 116, 117, 118, 141],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "💻 برمجة 1": {
                    "gate1": [33, 34, 35, 36, 37, 38, 39],
                    "komit1": [117, 118, 119, 120, 121, 122, 123],
                    "student_written1": [101, 102, 103, 104, 105, 144],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "📊 تحليل 1": {
                    "gate1": [0],
                    "komit1": [110, 111, 112, 113, 114, 115],
                    "student_written1": [0],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "🖥 مبادئ عمل الحاسوب": {
                    "gate1": [0],
                    "komit1": [0],
                    "student_written1": [125, 126, 127, 128, 129],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "➗ جبر لا خطي": {
                    "gate1": [0],
                    "komit1": [0],
                    "student_written1": [89, 90, 91, 92],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
            },
        },
        "الفصل الثاني": {
            "theoretical": {
                "➗ جبر خطي": {
                    "gate1": [0],
                    "komit1": [5, 7, 8, 9, 10, 95, 105, 129],
                    "student_written1": [72, 73, 74, 75, 76, 137, 148],
                    "summaries1": [0],
                    "exams1": [20],
                    "notes1": [0],
                },
                "⚡ فيزياء انصاف نواقل": {
                    "gate1": [26],
                    "komit1": [45, 46, 47, 90, 102, 103, 104],
                    "student_written1": [43, 44, 45, 46, 47, 48, 49],
                    "summaries1": [11, 12, 15, 19, 20, 27, 28],
                    "exams1": [23, 24],
                    "notes1": [37, 44],
                },
                "💻 برمجة 2": {
                    "gate1": [22, 23, 24, 25, 26, 48, 49, 57, 58, 59],
                    "komit1": [17, 18, 19, 20, 21, 22, 97, 106],
                    "student_written1": [172, 58, 59, 60, 61, 62, 63, 64, 171, 173, 165, 166, 167, 168, 169],
                    "summaries1": [0],
                    "exams1": [18],
                    "notes1": [0],
                },
                "📊 تحليل 2": {
                    "gate1": [0],
                    "komit1": [30, 31, 32, 33, 34, 35, 91, 130],
                    "student_written1": [66, 67, 68, 69, 70, 138, 149],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "🇬🇧 لغة انجليزية 2": {
                    "gate1": [61],
                    "komit1": [49],
                    "student_written1": [145],
                    "summaries1": [0],
                    "exams1": [13],
                    "notes1": [0],
                },
                "🔥 ثقافة عامة": {
                    "gate1": [0],
                    "komit1": [109],
                    "student_written1": [163],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [45, 46],
                },
            },
            "practical": {
                "➗ جبر خطي": {
                    "gate1": [30, 31],
                    "komit1": [12, 13, 14, 15, 80, 96, 125],
                    "student_written1": [0],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "⚡ فيزياء انصاف نواقل": {
                    "gate1": [0],
                    "komit1": [45, 46, 47, 90, 102, 103, 104],
                    "student_written1": [51, 52, 53, 54, 55, 56, 136],
                    "summaries1": [16, 17, 29],
                    "exams1": [0],
                    "notes1": [0],
                },
                "💻 برمجة 2": {
                    "gate1": [28, 43, 44, 45, 46, 47, 53, 54, 55, 60],
                    "komit1": [24, 25, 26, 27, 28, 98, 99, 100, 101],
                    "student_written1": [150, 151, 152, 153, 154, 155, 156, 158, 159],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
                "📊 تحليل 2": {
                    "gate1": [0],
                    "komit1": [37, 38, 39, 40, 41, 42, 43, 92, 131],
                    "student_written1": [0],
                    "summaries1": [0],
                    "exams1": [0],
                    "notes1": [0],
                },
            },
        },
    },
    "السنة الثانية": {
        "الفصل الأول": {
            "theoretical": {
                "برمجة متقدمة 1": {
                    "gate2": [0],
                    "komit2": [7, 8, 11],
                    "student_written2": [4, 5, 6, 7, 8, 9, 10, 11],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "دارات كهربائية": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "احصاء واحتمالات": {
                    "gate2": [0],
                    "komit2": [31, 32],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "رياضيات متقطعة": {
                    "gate2": [0],
                    "komit2": [15, 16, 17, 18],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "تحليل 3": {
                    "gate2": [0],
                    "komit2": [23, 24, 25, 26],
                    "student_written2": [18, 19, 20, 21, 22, 23, 24],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "انكليزي معلوماتية 1": {
                    "notes2": [0],
                },
            },
            "practical": {
                "برمجة متقدمة 1": {
                    "gate2": [0],
                    "komit2": [12, 13, 14],
                    "student_written2": [12, 13, 14, 15, 16, 17],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "دارات كهربائية": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "احصاء واحتمالات": {
                    "gate2": [0],
                    "komit2": [33, 34, 35],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "رياضيات متقطعة": {
                    "gate2": [0],
                    "komit2": [21, 22],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "تحليل 3": {
                    "gate2": [0],
                    "komit2": [27, 28, 29, 30],
                    "student_written2": [18, 19, 20, 21, 22, 23, 24],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [6],
                },
            },
        },
        "الفصل الثاني": {
            "theoretical": {
                "برمجة متقدمة 2": {
                    "gate2": [6, 7, 8, 9, 10, 11, 12, 13],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "داتا 1": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [25, 26, 27, 28, 29, 30, 31],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "اشارات ونظم": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [50, 51, 52, 53, 54, 55, 56, 57],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "بحوث عمليات": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [37, 39, 40, 41, 42, 43, 44],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "تحليل عددي": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "انكليزي معلوماتية 2": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [65, 66],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
            },
            "practical": {
                "برمجة متقدمة 2": {
                    "gate2": [15, 16, 20, 17, 18, 21, 19],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "داتا 1": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [32, 33, 34, 35, 36],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [4, 5],
                },
                "اشارات ونظم": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [58, 59, 60, 61, 62, 63, 64],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "بحوث عمليات": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [45, 46, 47, 48, 49],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
                "تحليل عددي": {
                    "gate2": [0],
                    "komit2": [0],
                    "student_written2": [0],
                    "summaries2": [0],
                    "exams2": [0],
                    "notes2": [0],
                },
            },
        },
    },
    "السنة الثالثة": {
        "الفصل الأول": {
            "theoretical": {
                "خوارزميات وبنى المعطيات": {
                    "gate3": [119, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123],
                    "komit3": [71, 72, 73, 75, 76, 77, 78, 79, 80, 81],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظرية الحوسبة": {
                    "gate3": [154, 155, 156, 157, 158, 159, 160, 161, 162],
                    "komit3": [89, 90, 91, 94, 95, 96, 97, 98],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "اتصالات رقمية": {
                    "gate3": [132, 133, 136, 135],
                    "komit3": [100, 101, 102, 103, 104, 105],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "مهارات تواصل": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "دارات منطقية": {
                    "gate3": [125, 126, 127, 128, 129, 130],
                    "komit3": [130, 131, 132, 133, 134],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظم تشغيل 1": {
                    "gate3": [100, 103, 104, 105, 106, 107, 108, 109, 163, 164],
                    "komit3": [122, 123, 124, 125, 126, 127, 128],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [22],
                    "notes3": [0],
                },
            },
            "practical": {
                "خوارزميات وبنى المعطيات": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظرية الحوسبة": {
                    "gate3": [145, 146, 147, 148, 149, 150, 151, 152],
                    "komit3": [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "اتصالات رقمية": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "مهارات تواصل": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "دارات منطقية": {
                    "gate3": [138, 139, 140, 141, 142, 143],
                    "komit3": [107, 108, 109],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظم تشغيل 1": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
            },
        },
        "الفصل الثاني": {
            "theoretical": {
                "نظرية التعقيد": {
                    "gate3": [37, 38, 39, 40, 41, 42, 43, 88, 92, 91],
                    "komit3": [23, 24, 25, 26, 55, 56, 57, 58],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظرية المعلومات": {
                    "gate3": [57, 58, 59, 170, 171],
                    "komit3": [28, 31, 29, 30],
                    "student_written3": [108, 109, 110, 120, 121, 122],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "شبكات 1": {
                    "gate3": [82, 83, 84, 85, 86, 68, 69],
                    "komit3": [37],
                    "student_written3": [93, 94, 95, 96],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "بنيان 1": {
                    "gate3": [94, 95, 96, 97, 98],
                    "komit3": [43, 44],
                    "student_written3": [9, 12, 14, 16],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "مبادئ ذكاء صنعي": {
                    "gate3": [71, 72],
                    "komit3": [46],
                    "student_written3": [98, 99, 100, 101],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "هندسة برمجيات 1": {
                    "gate3": [12, 13, 14, 15, 16],
                    "komit3": [10, 11, 12, 13, 14, 15, 16],
                    "student_written3": [49, 51, 53, 56, 58, 60, 65, 130],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
            },
            "practical": {
                "نظرية التعقيد": {
                    "gate3": [0],
                    "komit3": [0],
                    "student_written3": [0],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [0],
                },
                "نظرية المعلومات": {
                    "gate3": [61],
                    "komit3": [33, 34, 35],
                    "student_written3": [124, 125, 126, 127, 128],
                    "summaries3": [0],
                    "exams3": [17, 18, 19],
                    "notes3": [0],
                },
                "شبكات 1": {
                    "gate3": [48, 49, 50, 51, 52, 53, 81],
                    "komit3": [39, 40, 41],
                    "student_written3": [67, 69, 71, 73, 75, 77, 79],
                    "summaries3": [0],
                    "exams3": [8, 11, 12, 13, 14, 15, 16],
                    "notes3": [15, 16, 19, 20],
                },
                "بنيان 1": {
                    "gate3": [21, 23, 25, 27, 29, 55],
                    "komit3": [5, 7, 8, 60],
                    "student_written3":
                    [31, 32, 33, 35, 37, 39, 41, 43, 45, 46],
                    "summaries3": [0],
                    "exams3": [0],
                    "notes3": [4, 5, 6, 7, 8, 9, 10, 11, 12, 18],
                },
                "مبادئ ذكاء صنعي": {
                    "gate3": [74, 75, 76, 77, 78, 79],
                    "komit3": [48, 49, 50, 51],
                    "student_written3": [103, 104, 105, 106],
                    "summaries3": [0],
                    "exams3": [6, 7],
                    "notes3": [0],
                },
                "هندسة برمجيات 1": {
                    "gate3": [33, 34, 35, 18, 19, 46],
                    "komit3": [18, 20, 21, 53],
                    "student_written3": [83, 85, 86, 87, 88, 89, 90, 91],
                    "summaries3": [0],
                    "exams3": [9],
                    "notes3": [0],
                },
            },
        },
    },
    "السنة الرابعة": {
        "specializations": {
            "هندسة البرمجيات": "p",
            "الشبكات والنظم": "n",
            "الذكاء الاصطناعي": "i"
        },
        "الفصل الأول": {
            "هندسة البرمجيات": {
                "theoretical": {
                    "هندسة برمجيات 2": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "داتا 2": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "رسم بمعونة الحاسب": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "إدارة منظمات": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                },
                "practical": {
                    "هندسة برمجيات 2": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "داتا 2": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "رسم بمعونة الحاسب": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "إدارة منظمات": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                },
            },
            "الشبكات والنظم": {
                "theoretical": {
                    "شبكات 2": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "نظم تشغيل 2": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "رسم بمعونة الحاسب": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "إدارة منظمات": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                },
                "practical": {
                    "شبكات 2": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "نظم تشغيل 2": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "رسم بمعونة الحاسب": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "إدارة منظمات": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                },
            },
            "الذكاء الاصطناعي": {
                "theoretical": {
                    "لغات برمجة": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "شبكات عصبونية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "خوارزميات بحث ذكية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "إدارة منظمات": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                },
                "practical": {
                    "لغات برمجة": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "شبكات عصبونية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "خوارزميات بحث ذكية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "برمجة تفرعية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "نظم وسائط متعددة": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "إدارة منظمات": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                },
            },
        },
        "الفصل الثاني": {
            "هندسة البرمجيات": {
                "theoretical": {
                    "نمذجة ومحاكاة": {
                        "gate4p": [36, 37, 38, 39, 40],
                        "komit4p": [26, 45, 46, 47],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [4],
                        "notes4p": [0],
                    },
                    "تحليل نظم مالية": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [5, 6, 7, 8, 9],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [4],
                    },
                    "بناء مترجمات": {
                        "gate4p": [20, 21, 22, 23],
                        "komit4p": [12, 13, 14, 15],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "تصميم تجارب": {
                        "gate4p": [0],
                        "komit4p": [8, 9, 10, 35, 37, 39],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "النظم الموزعة": {
                        "gate4p": [4, 5, 6, 7],
                        "komit4p": [21, 22, 40],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                },
                "practical": {
                    "نمذجة ومحاكاة": {
                        "gate4p": [12, 13, 14, 15, 16, 17],
                        "komit4p": [27, 29, 30, 31],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "تحليل نظم مالية": {
                        "gate4p": [0],
                        "komit4p": [0],
                        "student_written4p": [11, 12, 16, 17, 18],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [4],
                    },
                    "بناء مترجمات": {
                        "gate4p": [0],
                        "komit4p": [16, 17, 18, 44, 48],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "تصميم تجارب": {
                        "gate4p": [24, 25, 26, 27, 32, 33, 34, 35],
                        "komit4p": [5, 6, 7, 33, 34, 36, 49],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                    "النظم الموزعة": {
                        "gate4p": [8, 9, 10],
                        "komit4p": [23],
                        "student_written4p": [0],
                        "summaries4p": [0],
                        "exams4p": [0],
                        "notes4p": [0],
                    },
                },
            },
            "الشبكات والنظم": {
                "theoretical": {
                    "نمذجة ومحاكاة": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "بروتوكولات شبكية": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "بنيان 2": {
                        "gate4n": [0],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "تصميم تجارب": {
                        "gate4n": [0],
                        "komit4n": [8, 9, 10, 22, 24, 25],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "النظم الموزعة": {
                        "gate4n": [5, 6, 7, 8],
                        "komit4n": [12, 13, 26],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                },
                "practical": {
                    "نمذجة ومحاكاة": {
                        "gate4n": [0],
                        "komit4n": [18, 19, 20, 21],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "بروتوكولات شبكية": {
                        "gate4n": [18, 19, 20, 21, 22, 23],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "بنيان 2": {
                        "gate4n": [13, 14, 15, 16, 29],
                        "komit4n": [0],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "تصميم تجارب": {
                        "gate4n": [25, 26, 27, 28, 34, 35, 36, 37],
                        "komit4n": [5, 6, 7, 16, 17, 23, 27],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                    "النظم الموزعة": {
                        "gate4n": [9, 10, 11],
                        "komit4n": [14],
                        "student_written4n": [0],
                        "summaries4n": [0],
                        "exams4n": [0],
                        "notes4n": [0],
                    },
                },
            },
            "الذكاء الاصطناعي": {
                "theoretical": {
                    "تعلم الآلة": {
                        "gate4i": [0],
                        "komit4i": [11, 12],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "رؤية حاسوبية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "نظم قواعد معرفة": {
                        "gate4i": [0],
                        "komit4i": [],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "بناء مترجمات": {
                        "gate4i": [14, 15, 16, 17],
                        "komit4i": [18, 19, 20, 21],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "النظم الموزعة": {
                        "gate4i": [4, 5, 6, 7],
                        "komit4i": [27, 28, 37],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                },
                "practical": {
                    "تعلم الآلة": {
                        "gate4i": [0],
                        "komit4i": [13, 14, 15, 16],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "رؤية حاسوبية": {
                        "gate4i": [0],
                        "komit4i": [0],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "نظم قواعد معرفة": {
                        "gate4i": [0],
                        "komit4i": [32, 33, 34, 35, 36, 40, 41, 42],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "بناء مترجمات": {
                        "gate4i": [0],
                        "komit4i": [22, 23, 24, 38, 39],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                    "النظم الموزعة": {
                        "gate4i": [8, 9, 10],
                        "komit4i": [29],
                        "student_written4i": [0],
                        "summaries4i": [0],
                        "exams4i": [0],
                        "notes4i": [0],
                    },
                },
            },
        },
    },
    "السنة الخامسة": {
        "specializations": {
            "هندسة البرمجيات": "p",
            "الشبكات والنظم": "n",
            "الذكاء الاصطناعي": "i"
        },
        "الفصل الأول": {
            "هندسة البرمجيات": {
                "theoretical": {
                    "خوارزميات بحث ذكية": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "داتا 3": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "امن معلومات": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "تعليم الكتروني": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "تطبيقات الانترنت": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                },
                "practical": {
                    "خوارزميات بحث ذكية": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "داتا 3": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "امن معلومات": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "تعليم الكتروني": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "تطبيقات الانترنت": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                },
            },
            "الشبكات والنظم": {
                "theoretical": {
                    "نظم زمن حقيقي": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "نظم رقمية مبرمجة": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "امن معلومات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تعليم الكتروني": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تطبيقات الانترنت": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                },
                "practical": {
                    "نظم زمن حقيقي": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "نظم رقمية مبرمجة": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "امن معلومات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تعليم الكتروني": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تطبيقات الانترنت": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                },
            },
            "الذكاء الاصطناعي": {
                "theoretical": {
                    "الروبوتية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "المنطق الترجيحي": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "الحقائق الافتراضية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "إدارة المشاريع": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "امن معلومات": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                },
                "practical": {
                    "الروبوتية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "المنطق الترجيحي": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "الحقائق الافتراضية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "إدارة المشاريع": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "امن معلومات": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                },
            },
        },
        "الفصل الثاني": {
            "هندسة البرمجيات": {
                "theoretical": {
                    "نماذج تصميم": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "هندسة برمجيات 3": {
                        "gate5p": [4, 5, 6, 7, 8, 9, 10, 11],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "هندسة نظم معلومات": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "تسويق وجودة": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                },
                "practical": {
                    "نماذج تصميم": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "هندسة برمجيات 3": {
                        "gate5p": [13, 14, 15],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                    "هندسة نظم معلومات": {
                        "gate5p": [0],
                        "komit5p": [0],
                        "student_written5p": [0],
                        "summaries5p": [0],
                        "exams5p": [0],
                        "notes5p": [0],
                    },
                },
            },
            "الشبكات والنظم": {
                "theoretical": {
                    "تطبيقات شبكية": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تصميم شبكات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "إدارة شبكات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تسويق وجودة": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                },
                "practical": {
                    "تطبيقات شبكية": {
                        "gate5n": [0],
                        "komit5n": [5, 6, 7, 8, 9],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "تصميم شبكات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                    "إدارة شبكات": {
                        "gate5n": [0],
                        "komit5n": [0],
                        "student_written5n": [0],
                        "summaries5n": [0],
                        "exams5n": [0],
                        "notes5n": [0],
                    },
                },
            },
            "الذكاء الاصطناعي": {
                "theoretical": {
                    "استكشاف المعرفة": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "معالجة اللغات الطبيعية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "التعليم التلقائي": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "تسويق وجودة": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                },
                "practical": {
                    "استكشاف المعرفة": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "معالجة اللغات الطبيعية": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                    "التعليم التلقائي": {
                        "gate5i": [0],
                        "komit5i": [0],
                        "student_written5i": [0],
                        "summaries5i": [0],
                        "exams5i": [0],
                        "notes5i": [0],
                    },
                },
            },
        },
    },
}

channel_ids = {
    # السنة الأولى
    "gate1": -1002739707573,
    "komit1": -1002883141998,
    "student_written1": -1002701154329,
    "summaries1": -1002890234972,
    "exams1": -1002449310532,
    "notes1": -1002834270732,

    # السنة الثانية
    "gate2": -1002651836647,  # سيتم تحديثها لاحقاً
    "komit2": -1002534769253,
    "student_written2": -1002721628683,
    "summaries2": -1002621858994,
    "exams2": -1002852495855,
    "notes2": -1002600270416,

    # السنة الثالثة
    "gate3": -1002721306714,
    "komit3": -1002626373818,
    "student_written3": -1002827083356,
    "summaries3": -1002716898285,
    "exams3": -1002634922150,
    "notes3": -1002832147740,

    # السنة الرابعة - هندسة البرمجيات
    "gate4p": -1002869327000,
    "komit4p": -1002878741842,
    "student_written4p": -1002723903454,
    "summaries4p": -1002822605673,
    "exams4p": -1002744540625,
    "notes4p": -1002744363447,

    # السنة الرابعة - الشبكات والنظم
    "gate4n": -1002803525724,
    "komit4n": -1002806368893,
    "student_written4n": -1002833015956,
    "summaries4n": -1002607963545,
    "exams4n": -1002792554456,
    "notes4n": -1002882181611,

    # السنة الرابعة - الذكاء الاصطناعي
    "gate4i": -1002759333456,
    "komit4i": -1002705201493,
    "student_written4i": -1002387577544,
    "summaries4i": -1002677276057,
    "exams4i": -1002866468744,
    "notes4i": -1002649600575,

    # السنة الخامسة - هندسة البرمجيات
    "gate5p": -1002644530568,
    "komit5p": -1002701442563,
    "student_written5p": -10025001231172,
    "summaries5p": -1002704130539,
    "exams5p": -1002765971652,
    "notes5p": -1002336787387,

    # السنة الخامسة - الشبكات والنظم
    "gate5n": -1002577235956,
    "komit5n": -1002730578201,
    "student_written5n": -1002784372364,
    "summaries5n": -1002653148173,
    "exams5n": -1002696838873,
    "notes5n": -1002755726721,

    # السنة الخامسة - الذكاء الاصطناعي
    "gate5i": -1002653331410,
    "komit5i": -1002671832126,
    "student_written5i": -1002501807711,
    "summaries5i": -1002809488273,
    "exams5i": -1002397729113,
    "notes5i": -1002709871937,
}


# معرفات قنوات برامج الامتحانات
exam_schedules_channels = {
    # الهندسة المعلوماتية
    "informatics_theoretical_exam": -1002430206491,  
    "informatics_practical_exam": -1002430206491,  

}

exam_schedules_messages = {
    "informatics_theoretical_exam": 7,
    "informatics_practical_exam": 0,
}